### PR TITLE
Ability to set a custom title

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by LarsWiegers** [comment]
Hey Mohammed, Thanks for creating a pr. If you could put the old text for the title back ( someone might depend upon it) you have my approval for the pr.

**Comment by mohamedsabil83** [comment]
> Hey Mohammed, Thanks for creating a pr. If you could put the old text for the title back ( someone might depend upon it) you have my approval for the pr.

Sure, I'll do it now

**Comment by LarsWiegers** [comment]
@mohamedsabil83 thanks for creating this pr. good job 💪

**Comment by mohamedsabil83** [comment]
You're welcome

**Pull request merged**
