### PR TITLE
Added Custom InfoWindow and Icon on Google Maps

### PR DESCRIPTION
**Pull request by kikojover**
Hi Lars, this is a great package!!
 In one of my projects i need InfoWindow and custom icons on Google Map.
I've added this ability to blade template.
Hope is useful and you accept PR
Thanks for your work

### CODE REVIEW

**Comment by LarsWiegers** [comment]
Hi @kikojover, thx for the kind words! 

Love the idea and the pr.  Do you use the package only for google maps?

I would love to keep the api for both the map types ( google map and leaflet ) the same.

If you add tests for the google maps info window, I can add the version for leaflet + tests. 

Sounds like a deal?

**Comment by kikojover** [comment]
Sure it's a deal!! :-)
Only let me use a couple of days to add the tests, sorry, I'm a newbie in the PR World.

About your question, it's the first time I have used your package, my current project requires Google Maps, so the answer is yes, i use your package only for Google Maps (for the moment ;-)), but I hope use leaflet too in he future.

A question about PR,  i must send another PR with the tests or it's possible to include it in current one? (As you told I'm a newbie ...)

Thank you.

**Comment by LarsWiegers** [comment]
Hey, you can add the tests to this pr.

**Comment by kikojover** [comment]
Hi @LarsWiegers , i've added Unit tests to Google Maps :-)

**Comment by LarsWiegers** [comment]
@kikojover I have merged the changes + made a new release

**Pull request merged**
